---
- name: restart logrotate
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
    daemon_reload: true
  loop: "{{ logrotate_services | flatten }}"
  when: logrotate_enable is true
  listen: restart_logrotate
